/*
 Matthew Ludwig
 This is where the lesson for the pokemon fundementals begin
*/

package pokemonGuide;

/**
 *
 * @author malud0519
 */
import java.util.*; 
public class basicLesson extends javax.swing.JFrame {

    /**
     * Creates new form basicLesson
     */
    
    ArrayList <String> type = new ArrayList <>();
    
    public basicLesson() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSpinner1 = new javax.swing.JSpinner();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputText = new javax.swing.JTextArea();
        statboosts = new javax.swing.JRadioButton();
        rng = new javax.swing.JRadioButton();
        typeMatchup = new javax.swing.JRadioButton();
        natures = new javax.swing.JRadioButton();
        basestats = new javax.swing.JRadioButton();
        items = new javax.swing.JRadioButton();
        ivs = new javax.swing.JRadioButton();
        moves = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        goBack = new javax.swing.JMenuItem();
        reset = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(51, 0, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Introduction ");

        outputText.setEditable(false);
        outputText.setColumns(20);
        outputText.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        outputText.setRows(5);
        outputText.setText("By now you have started pokemon, but you \nprobably have some questions about pokemon \nbattling. There are many different mechanics\nthat influence the attack damage and the \namount of damage taken. In total, there are \n5 different pokemon stats which affect the\ndamage. These are HP, Attack, Defense, Special\nAttack and Special Defense. Each of these are\nset prior to each battle but, they can be \nincreased using stat boosts.You can choose \nwhich topic to learn more about below.");
        jScrollPane1.setViewportView(outputText);

        buttonGroup1.add(statboosts);
        statboosts.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        statboosts.setForeground(new java.awt.Color(0, 51, 255));
        statboosts.setText("Stat Boosts");
        statboosts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statboostsActionPerformed(evt);
            }
        });

        buttonGroup1.add(rng);
        rng.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rng.setForeground(new java.awt.Color(255, 51, 51));
        rng.setText("RNG");
        rng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rngActionPerformed(evt);
            }
        });

        buttonGroup1.add(typeMatchup);
        typeMatchup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        typeMatchup.setForeground(new java.awt.Color(255, 102, 51));
        typeMatchup.setText("Type Matchups");
        typeMatchup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeMatchupActionPerformed(evt);
            }
        });

        buttonGroup1.add(natures);
        natures.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        natures.setForeground(new java.awt.Color(51, 0, 153));
        natures.setText("Natures");
        natures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naturesActionPerformed(evt);
            }
        });

        buttonGroup1.add(basestats);
        basestats.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        basestats.setForeground(new java.awt.Color(0, 153, 51));
        basestats.setText("Base Stats");
        basestats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basestatsActionPerformed(evt);
            }
        });

        buttonGroup1.add(items);
        items.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        items.setForeground(new java.awt.Color(255, 51, 0));
        items.setText("Items");
        items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsActionPerformed(evt);
            }
        });

        buttonGroup1.add(ivs);
        ivs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ivs.setForeground(new java.awt.Color(0, 0, 255));
        ivs.setText("IV's and EV's");
        ivs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivsActionPerformed(evt);
            }
        });

        buttonGroup1.add(moves);
        moves.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        moves.setForeground(new java.awt.Color(102, 102, 0));
        moves.setText("Moves");
        moves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Available Topics");

        jButton1.setText("Go");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statboosts)
                                    .addComponent(rng, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(basestats)
                                    .addComponent(typeMatchup))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(items)
                                    .addComponent(natures))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(moves)
                                    .addComponent(ivs)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jButton1)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statboosts)
                    .addComponent(typeMatchup)
                    .addComponent(natures)
                    .addComponent(moves))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(items)
                    .addComponent(ivs)
                    .addComponent(basestats)
                    .addComponent(rng))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jMenu1.setText("Help");

        goBack.setText("Go Back");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });
        jMenu1.add(goBack);

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jMenu1.add(reset);

        Exit.setText("Exit Program");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        this.dispose();
        basicGuide pretest = new basicGuide();
        pretest.setVisible(true);
    }//GEN-LAST:event_goBackActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        if (evt.getSource() == reset) {
            dispose();
            basicLesson resetProgram = new basicLesson();
            resetProgram.setVisible(true);
        }
    }//GEN-LAST:event_resetActionPerformed

    private void typeMatchupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeMatchupActionPerformed
      jButton1.setEnabled(true);
      type.add(0,"Fire");
      type.add(1, "Water");
      type.add(2, "Grass");
      type.add(3, "Bug");
      type.add(4, "Flying");
      type.add(5, "Normal");
      type.add(6, "Rock");
      type.add(7, "Fighting");
      type.add(8, "Ice");
      type.add(9, "Ghost");
      type.add(10, "Ground");
      type.add(11, "Lightning");
      type.add(12, "Dragon");
      type.add(13, "Psychic");
      type.add(14, "Poison");
      type.add(15, "Fairy");
      
      for (int i = 0; i < type.size(); i++) {
         
      }
      
    }//GEN-LAST:event_typeMatchupActionPerformed

    private void rngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rngActionPerformed
        jButton1.setEnabled(true);
    }//GEN-LAST:event_rngActionPerformed

    private void statboostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statboostsActionPerformed
        jButton1.setEnabled(true);
    }//GEN-LAST:event_statboostsActionPerformed

    private void naturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naturesActionPerformed
        jButton1.setEnabled(true);
    }//GEN-LAST:event_naturesActionPerformed

    private void movesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movesActionPerformed
        jButton1.setEnabled(true);
    }//GEN-LAST:event_movesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        title.setText("");
        outputText.setText("");
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void basestatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basestatsActionPerformed
        jButton1.setEnabled(true);
    }//GEN-LAST:event_basestatsActionPerformed

    private void itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsActionPerformed
        jButton1.setEnabled(true);
    }//GEN-LAST:event_itemsActionPerformed

    private void ivsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivsActionPerformed
        jButton1.setEnabled(true);
    }//GEN-LAST:event_ivsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(basicLesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(basicLesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(basicLesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(basicLesson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new basicLesson().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JRadioButton basestats;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem goBack;
    private javax.swing.JRadioButton items;
    private javax.swing.JRadioButton ivs;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JRadioButton moves;
    private javax.swing.JRadioButton natures;
    private javax.swing.JTextArea outputText;
    private javax.swing.JMenuItem reset;
    private javax.swing.JRadioButton rng;
    private javax.swing.JRadioButton statboosts;
    private javax.swing.JLabel title;
    private javax.swing.JRadioButton typeMatchup;
    // End of variables declaration//GEN-END:variables
}
